### ISSUE TITLE
use for lua-handlers?

### ISSUE THREAD

**Issue by fslove** [brimworks/lua-http-parser#7]
have any examples ?
e.g. http://127.0.0.1:9090/hello_api
how to get body?
thanks.

**Comment by brimworks** [comment]
Tests are here:

https://github.com/brimworks/lua-http-parser/blob/master/test.lua

Note that this is only an HTTP parser... it doesn't open TCP sockets, so it is not a complete solution for fetching data from arbitrary URLs.

**Comment by moteus** [comment]
You can try my port of [Pegasus](https://luarocks.org/modules/moteus/pegasus) server with this parser
