### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by szl-926929** [brimworks/lua-http-parser#8]
luarocks install lua-http-parse
raise err:
Installing https://luarocks.org/lua-http-parser-2.7-0.src.rock...
Using https://luarocks.org/lua-http-parser-2.7-0.src.rock... switching to 'build' mode
gcc -O2 -fPIC -I/usr/include -c http-parser/http_parser.c -o http-parser/http_parser.o
gcc -O2 -fPIC -I/usr/include -c lua-http-parser.c -o lua-http-parser.o
lua-http-parser.c:2:21: fatal error: lauxlib.h: No such file or directory
 #include <lauxlib.h>
                     ^
compilation terminated.

Error: Build error: Failed compiling object lua-http-parser.o

**Comment by brimworks** [comment]
I'll take a look when I get a chance. What version of lua and luarocks do you have installed, and which OS?

**Comment by brimworks** [comment]
No response, so I'm closing. Note that this error indicates that the Lua header files where not found in /usr/include (and luarocks somehow missed finding them in a different directory).
